### ISSUE TITLE
Current text field inside of sticky note allows the user to type beyond the sticky note dimensions

### ISSUE THREAD

**Issue by tennitech** [PiersonG33/PosterBoy#130]
Need to constrain the sticky note's text field so that it doesn't escape the boundaries of it.

**Comment by telescopeman** [comment]
Javascript seemingly doesn't handle this in a natural way. We could maybe do it in a cludgy way by limiting both character count and whitespace? Idk

**Comment by telescopeman** [comment]
Fixed. There is now a 150 char limit, and you aren't able to put in newlines at all.
